/* Generated By:JavaCC: Do not edit this line. JsonDriverConstants.java */
package com.github.gchudnov.jaxzilla.internal;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface JsonDriverConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int COMMA = 3;
  /** RegularExpression Id. */
  int LBRACE = 4;
  /** RegularExpression Id. */
  int RBRACE = 5;
  /** RegularExpression Id. */
  int COLON = 6;
  /** RegularExpression Id. */
  int LBRACKET = 7;
  /** RegularExpression Id. */
  int RBRACKET = 8;
  /** RegularExpression Id. */
  int ZERO = 9;
  /** RegularExpression Id. */
  int DIGIT_NONZERO = 10;
  /** RegularExpression Id. */
  int DIGIT = 11;
  /** RegularExpression Id. */
  int EXPONENT = 12;
  /** RegularExpression Id. */
  int FRACTION = 13;
  /** RegularExpression Id. */
  int NUMBER_INTEGER = 14;
  /** RegularExpression Id. */
  int NUMBER_DECIMAL = 15;
  /** RegularExpression Id. */
  int TRUE = 16;
  /** RegularExpression Id. */
  int FALSE = 17;
  /** RegularExpression Id. */
  int NULL = 18;
  /** RegularExpression Id. */
  int QUOTE = 19;
  /** RegularExpression Id. */
  int HEX = 20;
  /** RegularExpression Id. */
  int UNICODE = 21;
  /** RegularExpression Id. */
  int STRING_BODY = 22;
  /** RegularExpression Id. */
  int STRING = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<EOL>",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\"0\"",
    "<DIGIT_NONZERO>",
    "<DIGIT>",
    "<EXPONENT>",
    "<FRACTION>",
    "<NUMBER_INTEGER>",
    "<NUMBER_DECIMAL>",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"\\\"\"",
    "<HEX>",
    "<UNICODE>",
    "<STRING_BODY>",
    "<STRING>",
  };

}
