addSbtPlugin("ch.epfl.scala"     % "sbt-version-policy" % "2.0.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"       % "2.4.3")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"        % "0.6.0")
addSbtPlugin("com.github.gseitz" % "sbt-release"        % "1.0.13")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"            % "2.1.1")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"       % "3.9.10")
